import { ChatConversation, ChatMessage, LinkedDevice } from '../types/chat';
import { generateSafetyNumber } from './cryptoSecurity';

export const INITIAL_CONVERSATIONS: ChatConversation[] = [
  {
    id: 'gemini-bot',
    name: 'Gemini AI Assistant',
    avatar: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150&auto=format&fit=crop&q=80',
    isGroup: false,
    isOnline: true,
    lastSeen: 'online',
    unreadCount: 0,
    disappearingDefault: 0,
    isGeminiBot: true,
    geminiModel: 'gemini-3.8-flash',
    geminiRole: 'Discreet Cryptographic & Security Advisor',
    verifiedSafetyNumber: true,
    safetyCodeMatrix: generateSafetyNumber('me', 'gemini-bot'),
  },
  {
    id: 'group-aegis',
    name: 'Aegis Security Council',
    avatar: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=150&auto=format&fit=crop&q=80',
    isGroup: true,
    isOnline: true,
    unreadCount: 2,
    disappearingDefault: 86400, // 24 hours
    privacySettings: {
      adminsOnlySend: false,
      adminsOnlyEdit: true,
      whoCanAdd: 'admins',
      readReceipts: true,
      disappearingDefault: 86400,
    },
    participants: [
      { id: 'me', name: 'You (Host)', avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80', role: 'admin' },
      { id: 'u-elena', name: 'Elena Rostova', avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80', role: 'admin', status: 'Keyholder' },
      { id: 'u-marcus', name: 'Marcus Vance', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80', role: 'member', status: 'Operations' },
      { id: 'u-sarah', name: 'Dr. Sarah Chen', avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80', role: 'member', status: 'Security Lab' },
    ],
    verifiedSafetyNumber: true,
    safetyCodeMatrix: generateSafetyNumber('me', 'group-aegis'),
  },
  {
    id: 'contact-elena',
    name: 'Elena Rostova',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    isGroup: false,
    isOnline: true,
    lastSeen: 'online',
    unreadCount: 1,
    disappearingDefault: 10, // 10 seconds ephemeral
    verifiedSafetyNumber: true,
    safetyCodeMatrix: generateSafetyNumber('me', 'contact-elena'),
  },
  {
    id: 'contact-marcus',
    name: 'Marcus Vance',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    isGroup: false,
    isOnline: false,
    lastSeen: 'yesterday at 21:44',
    unreadCount: 0,
    disappearingDefault: 0,
    verifiedSafetyNumber: true,
    safetyCodeMatrix: generateSafetyNumber('me', 'contact-marcus'),
  },
  {
    id: 'contact-sarah',
    name: 'Dr. Sarah Chen',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    isGroup: false,
    isOnline: false,
    lastSeen: 'today at 07:15',
    unreadCount: 0,
    disappearingDefault: 0,
    verifiedSafetyNumber: true,
    safetyCodeMatrix: generateSafetyNumber('me', 'contact-sarah'),
  },
];

export const INITIAL_MESSAGES: Record<string, ChatMessage[]> = {
  'gemini-bot': [
    {
      id: 'm-gem-1',
      chatId: 'gemini-bot',
      senderId: 'gemini-bot',
      senderName: 'Gemini AI Assistant',
      senderAvatar: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150&auto=format&fit=crop&q=80',
      text: "Hello! I am your AI assistant within WhisperPulse. I can answer complex security questions, summarize files, convert text to speech, and brainstorm strategies across multiple models like Gemini 3.8 Flash and Gemini 3.1 Pro.",
      timestamp: Date.now() - 1000 * 60 * 30,
      status: 'read',
      isEncrypted: true,
    },
    {
      id: 'm-gem-2',
      chatId: 'gemini-bot',
      senderId: 'me',
      senderName: 'You',
      text: "Can you help me verify whether our voice calls and disappearing media comply with zero-knowledge standards?",
      timestamp: Date.now() - 1000 * 60 * 25,
      status: 'read',
      isEncrypted: true,
    },
    {
      id: 'm-gem-3',
      chatId: 'gemini-bot',
      senderId: 'gemini-bot',
      senderName: 'Gemini AI Assistant',
      senderAvatar: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150&auto=format&fit=crop&q=80',
      text: "Yes, WhisperPulse employs the Double Ratchet Protocol with Curve25519 and AES-256-GCM. Voice calls generate ephemeral session keys exchanged out-of-band, and view-once media is wiped from device memory immediately upon closure.",
      timestamp: Date.now() - 1000 * 60 * 20,
      status: 'read',
      isEncrypted: true,
      reactions: { '👍': ['You'], '🔒': ['Gemini AI Assistant'] },
    },
  ],
  'group-aegis': [
    {
      id: 'm-aeg-1',
      chatId: 'group-aegis',
      senderId: 'u-elena',
      senderName: 'Elena Rostova',
      senderAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      text: "Welcome to the Aegis Security Group. Messages in this thread are configured to disappear after 24 hours.",
      timestamp: Date.now() - 1000 * 60 * 60 * 2,
      status: 'read',
      isEncrypted: true,
      isDisappearing: true,
      disappearingDuration: 86400,
    },
    {
      id: 'm-aeg-2',
      chatId: 'group-aegis',
      senderId: 'u-marcus',
      senderName: 'Marcus Vance',
      senderAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      text: "I've uploaded the cross-device sync architecture sheet. It's stored in our offline document vault and also ready to sync to Google Drive.",
      timestamp: Date.now() - 1000 * 60 * 45,
      status: 'read',
      isEncrypted: true,
      mediaType: 'document',
      documentMeta: {
        name: 'Cross_Device_Sync_Architecture.sheet',
        size: '110 KB',
        type: 'sheet',
        cachedOffline: true,
      },
      reactions: { '📁': ['Elena Rostova', 'You'], '❤️': ['Dr. Sarah Chen'] },
    },
    {
      id: 'm-aeg-3',
      chatId: 'group-aegis',
      senderId: 'u-sarah',
      senderName: 'Dr. Sarah Chen',
      senderAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
      text: "Confirmed. Offline accessibility is working smoothly even without WiFi.",
      timestamp: Date.now() - 1000 * 60 * 5,
      status: 'delivered',
      isEncrypted: true,
    },
  ],
  'contact-elena': [
    {
      id: 'm-ele-1',
      chatId: 'contact-elena',
      senderId: 'u-elena',
      senderName: 'Elena Rostova',
      senderAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      text: "Hey! Sending you the sensitive biometric enclave photo. It is set as View-Once: once you open and dismiss it, it permanently dissolves from both of our devices.",
      timestamp: Date.now() - 1000 * 60 * 15,
      status: 'read',
      isEncrypted: true,
    },
    {
      id: 'm-ele-2',
      chatId: 'contact-elena',
      senderId: 'u-elena',
      senderName: 'Elena Rostova',
      senderAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      text: 'View-Once Encrypted Photo',
      timestamp: Date.now() - 1000 * 60 * 14,
      status: 'read',
      isEncrypted: true,
      isViewOnce: true,
      isViewed: false,
      mediaType: 'image',
      mediaUrl: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&auto=format&fit=crop&q=80',
    },
    {
      id: 'm-ele-3',
      chatId: 'contact-elena',
      senderId: 'u-elena',
      senderName: 'Elena Rostova',
      senderAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      text: "Also, this message will self-destruct in 10 seconds once read. Tap the audio button to hear it synthesized!",
      timestamp: Date.now() - 1000 * 60 * 1,
      status: 'delivered',
      isEncrypted: true,
      isDisappearing: true,
      disappearingDuration: 10,
    },
  ],
  'contact-marcus': [
    {
      id: 'm-mar-1',
      chatId: 'contact-marcus',
      senderId: 'u-marcus',
      senderName: 'Marcus Vance',
      senderAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      text: 'Check this confidential briefing document. We have it indexed for offline reading.',
      timestamp: Date.now() - 1000 * 60 * 60 * 20,
      status: 'read',
      isEncrypted: true,
      mediaType: 'document',
      documentMeta: {
        name: 'End_to_End_Protocol_v4.pdf',
        size: '1.4 MB',
        type: 'pdf',
        cachedOffline: true,
      },
    },
  ],
  'contact-sarah': [
    {
      id: 'm-sar-1',
      chatId: 'contact-sarah',
      senderId: 'u-sarah',
      senderName: 'Dr. Sarah Chen',
      senderAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
      text: 'Voice note: Voice calls are authenticated with 256-bit ephemeral keys. You can listen or call me anytime.',
      timestamp: Date.now() - 1000 * 60 * 60 * 10,
      status: 'read',
      isEncrypted: true,
      mediaType: 'audio',
      audioDuration: 8,
    },
  ],
};

export const INITIAL_DEVICES: LinkedDevice[] = [
  {
    id: 'dev-1',
    name: 'Chrome Web (This Computer)',
    platform: 'web',
    location: 'London, UK',
    lastActive: 'Active now',
    isCurrent: true,
    status: 'active',
  },
  {
    id: 'dev-2',
    name: 'iPhone 16 Pro Max',
    platform: 'ios',
    location: 'London, UK',
    lastActive: '12 seconds ago',
    isCurrent: false,
    status: 'active',
  },
  {
    id: 'dev-3',
    name: 'MacBook Pro M3 Max',
    platform: 'mac',
    location: 'London, UK',
    lastActive: '5 minutes ago',
    isCurrent: false,
    status: 'idle',
  },
  {
    id: 'dev-4',
    name: 'Samsung Galaxy Tab S9',
    platform: 'android',
    location: 'Office Desk',
    lastActive: 'Yesterday',
    isCurrent: false,
    status: 'idle',
  },
];
